---
title: "Readme"
output: html_document
---
This repository contains following files:
Assn4_Readme.md - brief description
Assn4_Run_analysis.R - script with comments
tidyset.txt - final tidy dataset
Assn4_CodeBook.md - tidyset description

Assn4_run-analysis.R script does this:
1) Merges the training and the test sets to create one data set.
2) Extracts only the measurements on the mean and standard deviation for each measurement.
3) Uses descriptive activity names to name the activities in the data set
4) Appropriately labels the data set with descriptive variable names.
5) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
This tidyset.txt is also uploaded on coursera server.

###Part1: Create merged Full dataset

Read all the data from both sets to their own data.tables  
Test set: 2947 measurements,   
Train set: 7352.  

```
#---------------------Get/load packages, we will be using-----------------------------------
install.packages("data.table", "dplyr", "plyr")
library (data.table, dplyr, plyr)

#set directory with data files, in my case: setwd("~/Dropbox/Study/DataScienceSpec/DataCleaning")--------------------------


#--------------------Load data files--------------------------------------------
X_test <- readLines("UCI HAR Dataset/test/X_test.txt")
labels_test <- readLines("UCI HAR Dataset/test/y_test.txt")
subject_test <- readLines("UCI HAR Dataset/test/subject_test.txt")
X_train <- readLines("UCI HAR Dataset/train/X_train.txt")
labels_train <- readLines("UCI HAR Dataset/train/y_train.txt")
subject_train <- readLines("UCI HAR Dataset/train/subject_train.txt")
```

Get all the variables with mean() and std() (this will give 79 variables in total) and write them in names_ms vector  

```
features_list <- readLines("UCI HAR Dataset/features.txt")
mean_var <- grep("mean()", features_list) #select all names order numbers with "mean()"
std_var <- grep("std()", features_list) #select all names order numbers with "std()"
mean_std <- sort(c(mean_var, std_var)) #all names numbers for mean and std together, ordered
names_list <- features_list[mean_std] #all NAMES with mean and std
#names in names_list look like "1 tBodyAcc-mean()-X", but I want to keep only "tBodyAcc-mean()-X" part. To delete these numbers:
names_ms <- c(substring(names_list[c(1:6)],3), substring(names_list[c(7:16)], 4), substring(names_list[c(17:79)], 5)) 
```

Transform X into a set of columns, labeled according to Y  

```
trim2 <- function (var, n) {
        x <- c()
        y <- cbind()
        for (i in 1:n) {
        x <- as.numeric(as.character(data.frame(strsplit(var[i], " +"))[,1]))
        m <- length(x)
        x <- x[mean_std+1]
        y <- rbind(y,x)}
        colnames(y) <- names_ms
        rownames(y) <- c(1:n)
        y}

trimmed_test2 <- trim2(X_test, length(X_test))
trimmed_train2 <- trim2(X_train, length(X_train))
```
Check dimension of a result, remember, we have 79 variables, so it should be like this:

```
dim(trimmed_test2)
```
[1] 2947   79

```
dim(trimmed_train2)
```
[1] 7352   79


Now merge together observations, subjects and activities in a single table - first for test set:

```
library(data.table)
test_set <- data.table(obs= 1: length(X_test), subject = subject_test, activity = labels_test, trimmed_test2)
```
Again check dimension of a result, remember, we have 79 variables + subject + activity + we introduced obs for obsevation number here, so 82 in total  

```
dim(test_set)
```
[1] 2947   82  

Then the same for train set:

```
train_set <- data.table(obs= (length(X_test)+1): (length(X_train)+length(X_test)), subject = subject_train, activity = labels_train, trimmed_train2) #here we create continuous numbering, test observations will be from 1 to 2947 and train from 2948 to 10299 
dim(train_set)
```
[1] 7352   82


Merge test and train sets

```
fullset <- rbind(test_set, train_set)
```

Relabel

```
#----Check activities naming:----------------------------------------------
> activities <- readLines("UCI HAR Dataset/activity_labels.txt")
> activities
```

[1] "1 WALKING"            "2 WALKING_UPSTAIRS"   "3 WALKING_DOWNSTAIRS" "4 SITTING"           
[5] "5 STANDING"           "6 LAYING"

```
#----Create relabeling vector:--------------------------------------------
activities <- c("WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING")

#----Relabel function-----------------------------------------------------
relabel <- function(m, activities){
        for (i in 1:length(m)) {
        x <- m[i]
        m[i]<- activities[as.numeric(x)]}
        m}

#----Relabelling----------------------------------------------------------  
fullset2 <- fullset #Here I keep original fullset unaltered just in case
fullset2$activity <- relabel(fullset2$activity, activities) #relabel activitiy row

```

###Part2: Create tidy set    


```
library(plyr)
```

------------------*This is explanation of the idea behind making tidy dataset, can be skipped*------------------------
```
#-----Count average for one variable by subject and activity---------------------------
s <- fullset2[,.(mean(`1 tBodyAcc-mean()-X`)), by=.(subject, activity)]
```

This is what now s looks like:  
  subject           activity        V1  
  1:       2           STANDING 0.2779115  
  2:       2            SITTING 0.2770874  
  3:       2             LAYING 0.2813734  
  4:       2            WALKING 0.2764266  
  5:       2 WALKING_DOWNSTAIRS 0.2776153  
 ---                                       
176:      30            SITTING 0.2683361  
177:      30             LAYING 0.2810339  
178:      30            WALKING 0.2764068  
179:      30 WALKING_DOWNSTAIRS 0.2831906  
180:      30   WALKING_UPSTAIRS 0.2714156      

Then we should add rows with other variables:

```
s2 <- fullset2[,.(mean(`2 tBodyAcc-mean()-Y`)), by=.(subject, activity)] #create a table for 2nd variable
cbind(s, s2$V1) #cbind last row of this table to our table
s3 <- fullset2[,.(mean(`3 tBodyAcc-mean()-Z`)), by=.(subject, activity)]
cbind(s, s2$V1, s3$V1)
```
I printed the results here to ensure rbind worked as it supposed to:    
subject           activity        V1           V2          V3  
  1:       2           STANDING 0.2779115 -0.018420827 -0.10590854  
  2:       2            SITTING 0.2770874 -0.015687994 -0.10921827  
  3:       2             LAYING 0.2813734 -0.018158740 -0.10724561  
  4:       2            WALKING 0.2764266 -0.018594920 -0.10550036  
  5:       2 WALKING_DOWNSTAIRS 0.2776153 -0.022661416 -0.11681294  
 ---                                                                
176:      30            SITTING 0.2683361 -0.008047313 -0.09951545  
177:      30             LAYING 0.2810339 -0.019449410 -0.10365815  
178:      30            WALKING 0.2764068 -0.017588039 -0.09862471  
179:      30 WALKING_DOWNSTAIRS 0.2831906 -0.017438390 -0.09997814  
180:      30   WALKING_UPSTAIRS 0.2714156 -0.025331170 -0.12469749  
  
```
x<-cbind(s, s2$V1, s3$V1)
colnames(x) <- z[1:5] ## z contains fullset2 colnames
x
```

 obs            subject  activity 1 tBodyAcc-mean()-X 2 tBodyAcc-mean()-Y  
  1:   2           STANDING 0.2779115        -0.018420827         -0.10590854  
  2:   2            SITTING 0.2770874        -0.015687994         -0.10921827  
  3:   2             LAYING 0.2813734        -0.018158740         -0.10724561  
  4:   2            WALKING 0.2764266        -0.018594920         -0.10550036  
  5:   2 WALKING_DOWNSTAIRS 0.2776153        -0.022661416         -0.11681294  


that is nice, but we have 79 column names, and we do not want to type each separately! Let's make a list of names

```
z <- colnames(fullset2) 
as.name(z[8])
```
Output:
`5 tBodyAcc-std()-Y`   

Function as.name() returns variable name, in dplyr package we can use eval() on as.name() result to call the column
Great, so we found a way 1) to merge columns properly and 2) to call a column with a name from the list of column names.

Then we should do this for all 79 variables.

We have two options: we can make a function...  

```
#------------------Option 1: In the cycle!-----------------------------------------

tidy <- function(set){
    z <- colnames(set)
    s <- set[ , mean(eval(as.name(z[4]))), by=.(subject, activity)]
        for (i in 5:82){
        m <- fullset2[,mean(eval(as.name(z[i]))), by=.(subject, activity)]
        s <- cbind(s, m$V1)}
    colnames(s) <- z[2:82]

        }
```
...Or make it part of the script with no function. I used this option, as it is simpler and I use it only once.

--------------------*End of boring explanation*---------------------------



```
#--------------Option 2: No function:--------------------------

    z <- colnames(fullset2)
    s <- fullset2[ , mean(eval(as.name(z[4]))), by=.(subject, activity)]
            for (i in 5:82){
            m <- fullset2[,mean(eval(as.name(z[i]))), by=.(subject, activity)]
            s <- cbind(s, m$V1)}
        colnames(s) <- z[2:82]
```  
Now the result is formally correct, but looks as a mess because of strange ordering, so we will arrange it first by subject, then by activity

```
    s$subject <- as.numeric(s$subject) #subject was a character vector, we make it numeric
    s <- arrange(s, subject, activity) ##this is our final tidyset!
        

    write.table(s, file = "tidyset.txt", append = FALSE, quote = TRUE, sep = " ",
            eol = "\n", na = "NA", dec = ".", row.names = FALSE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")
    tidyset <- read.table("tidyset.txt")

```
Now our tidyset is ready.

        
        